spring:
  datasource:
    url: jdbc:h2.mem:testdb
    username: root
    password: toor
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    database-plataform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true